name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and package
        run: mvn clean package -B -DskipTests

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Version Bump and Changelog Update
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          npx semantic-release

      - name: Create Release Tag
        run: |
          TAG_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git tag -a "v$TAG_VERSION" -m "Release version $TAG_VERSION"

      - name: Push Tag to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin "v$TAG_VERSION"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v$TAG_VERSION" ./target/*.jar --title "Release $TAG_VERSION" --notes "Release notes go here"
